# block chain
version: 2.1
#blockonerecords A&R derrick E Henderson
lust4moneyent
  #Declare a dependency on the welcome-orb
  welcome: DoDirtyThaDon
# Orchestrate or schedule a set of jobs
workflows:dodirtythadon
  # Name the workflow "welcome"
  welcome: book a call today
    # Run the welcome/run job in its own container
    jobs:
      - welcome/run
